### PR TITLE
Remove private replays

### PR DESCRIPTION
**Pull request by jgdhs27**
There was a month-old comment that read `Private is deprecated; it will be removed soon`. I guess this was forgotten about. Therefore I removed it.

### CODE REVIEW

**Comment by raviddog** [comment]
Do you need to generate migrations again? Error seems to be complaining that the models dont match the migration database state

**Comment by jgdhs27** [comment]
> Do you need to generate migrations again? Error seems to be complaining that the models dont match the migration database state

I guess so. How do I do that?

**Comment by raviddog** [comment]
`py manage.py makemigrations`

**Comment by jgdhs27** [comment]
Thank you!

**Review by raviddog — APPROVED** [review]
Nice

**Pull request merged**
