### PR TITLE
Add a field specifying whether the player cleared or not.

### PR DESCRIPTION
**Pull request by n-rook**
In theory I think it's possible to get this information from some replays. I know lunarcast only asks about clear for EoSD/PCB. But I don't know how
:kyouko_pensive: #78

I was very lazy about actually displaying it on the replay details page, because I figure I'll wait for #94 to be submitted before merging this

### CODE REVIEW

**Comment by raviddog** [comment]
we can keep this as a user filled field for the games that dont store it, but most modern games keep track of this, its either clear or the stage the run made it to. i havent looked specifically at how this is stored but we can parse it.

**Comment by raviddog** [comment]
is it possible to open pull requests into your branch if i want to make changes here?

**Comment by n-rook** [comment]
It technically is; you can push a branch, and then open a pull request and set the target branch to this branch (`nrook/cleared`) rather than main. But I would recommend just telling me what I should do instead.

**Comment by n-rook** [comment]
Alternately I think it's OK if this goes in as-is, and then we improve it later by autodetecting clears on more games.

**Review by raviddog — APPROVED** [review]
yeah i think that can work for now

**Pull request merged**
