### PR TITLE
Add a suggested Git hook that runs flake8.

### PR DESCRIPTION
**Pull request by n-rook**
I got tired of the CI hook telling me flake8 didn't work. This way, I will be informed before submission.

### CODE REVIEW

**Comment by n-rook** [comment]
I'm going to leave this open for awhile until I decide I really like having a hook here. Of course, if anyone else wants it they can always just install it from here.

**Comment by raviddog** [comment]
does that nuke your push if flake8 blows up so i dont have to realise i forgot to fix it when opening the PR? the sooner you merge that the sooner we'll all get it then, im on board 👍

**Comment by n-rook** [comment]
Yeah. You have to have flake8 installed though (that is, it runs "flake8" on the CLI and if you don't have it installed, it will just say an error)

**Comment by n-rook** [comment]
Oh yeah, note that you have to install it yourself like it says in the md file

**Pull request merged**
