### PR TITLE
fix tickbox behaviour if page gets loaded with a box ticked

### PR DESCRIPTION
**Pull request by 32th-System**
This happens when the page gets loaded from going back from a replay page, or when reloading

### CODE REVIEW

**Comment by jgdhs27** [comment]
This doesn't fix the issue for me.
I am testing on edge btw, it seems to have the bug most consistently.

**Comment by 32th-System** [comment]
I tested in Firefox, I'll look into it. Maybe the load event isn't being triggered?

**Comment by 32th-System** [comment]
In Chromium, reloading doesn't leave the box ticked, and going back uses a cached version of the page that has the table fully intact

**Comment by 32th-System** [comment]
turns out Edge handles things a bit differently from Chromium sometimes. The correct event to use was `pageshow`

**Review by jgdhs27 — APPROVED** [review]
Cool 👍

**Comment by jgdhs27** [comment]
@32th-System could you please rebase/merge and re-run the tests? I've removed them for being flaky

**Pull request merged**
