### PR TITLE
Allow the site to respond to traffic from local.silentselene.net.

### PR DESCRIPTION
**Pull request by n-rook**
This address is just 127.0.0.1, but I think it can be more convenient to access this way.

### CODE REVIEW

**Comment by 32th-System** [comment]
so would "local.silentselene.net" be set in /etc/hosts?

**Comment by n-rook** [comment]
Nah, I literally went and put an A record at it for 127.0.0.1.

**Comment by 32th-System** [comment]
then you should also add an AAAA record for ::1

**Comment by n-rook** [comment]
Done

**Pull request merged**
