### PR TITLE
Replace emoji flags with SVGs.

### PR DESCRIPTION
**Pull request by n-rook**
Emoji flags aren't available everywhere; notably, Windows doesn't have them.

### CODE REVIEW

**Comment by n-rook** [comment]
Screenshot 2023-10-08 at 5 18 32 PM

**Review by jgdhs27 — CHANGES_REQUESTED** [review]
The US flag looks like this for me:

image

**Comment by jgdhs27** [comment]
> The US flag looks like this for me:
> 
> image

(The Japanese flag looks correct)

**Comment by n-rook** [comment]
Which browser do you use, so I can look into this?

The US flag is "really" much bigger than the Japanese one in the images, but it really shouldn't matter since I'm styling it with CSS (and it's SVG). So it must be a CSS browser issue for me to look into

**Comment by jgdhs27** [comment]
> Which browser do you use, so I can look into this?
> 
> The US flag is "really" much bigger than the Japanese one in the images, but it really shouldn't matter since I'm styling it with CSS (and it's SVG). So it must be a CSS browser issue for me to look into

Chrome on desktop

**Comment by n-rook** [comment]
Hmm... looks fine on my Windows machine too

**Comment by 32th-System** [comment]
It looks fine for me as well. It even shows up in the correct size in Internet Explorer
image

**Comment by jgdhs27** [comment]
> Hmm, I'm on Chrome too (on a mac).
> 
> Could you try a cache-invalidating refresh? If that doesn't work, could you upload an image of the CSS when inspecting the img element in Chrome? That is, this:
> 
> Screenshot 2023-10-09 at 11 37 07 AM
> I'll try it on my Windows machine too when I get home.

Oh, it works as soon as i invalidate the cache. Sorry about that!

**Review by jgdhs27 — APPROVED** [review]

**Comment by n-rook** [comment]
npnp, easy mistake to make. I've definitely been there

**Pull request merged**
