### PR TITLE
Rework leaderboard

### PR DESCRIPTION
**Pull request by jgdhs27**
image

- Replaces checkboxes with nice big buttons. Much prettier and easier to press!
- Only allow 0-1 option in each category to be selected (eg. disallow selecting both Reimu + Marisa at once)
  - This removes a feature, but saves you a click when you want to switch to just one category to another
  - It's also preparation for having simple url query strings for each category, like replays/th08?shot=youmu&route=final%20b

### CODE REVIEW

**Review by n-rook — CHANGES_REQUESTED** [review]
Nice, I mostly like it.

I'm concerned about the integration of the UX concept that clicking an active filter disables it. We don't do that on the leaderboard, and I think it would be hard for users to discover. I'd much prefer having an "All" button, as we do on the leaderboard.

A minor nitpick: On Chrome, if I hover between two buttons, I see an I-beam. I'm not sure why, but it'd be nice to get rid of that if you can figure it out.

**Comment by jgdhs27** [comment]
> I'm concerned about the integration of the UX concept that clicking an active filter disables it. We don't do that on the leaderboard, and I think it would be hard for users to discover. I'd much prefer having an "All" button, as we do on the leaderboard.

How do I set "All" up for translators? Is there a shared context? Should I invent a new one?

**Comment by n-rook** [comment]
In theory, you should invent a new one, with a description like "selecting all of a category".

I actually think this PR would be much simpler if you handled the "All" button exclusively on the frontend / js side. That is, had a button like the current filters, except it calls "onClickAll()" or something instead. That way you wouldn't have to make backend changes or pass the literal string "All" around anywhere. It's kind of redundant to be manually prepending the string "All" to all these different filter lists fetched from the database anyway.

**Comment by jgdhs27** [comment]
You're right, I was already working on having initial filters for the next PR, but that's overdoing it for now. This new version should be simpler.

**Comment by jgdhs27** [comment]
> Nice, I mostly like it.
> 
> I'm concerned about the integration of the UX concept that clicking an active filter disables it. We don't do that on the leaderboard, and I think it would be hard for users to discover. I'd much prefer having an "All" button, as we do on the leaderboard.
> 
> A minor nitpick: On Chrome, if I hover between two buttons, I see an I-beam. I'm not sure why, but it'd be nice to get rid of that if you can figure it out.
Can't reproduce

**Review by n-rook — APPROVED** [review]

**Pull request merged**
