### PR TITLE
Don't apply csrf for autodeploy, so webhooks can easily call it

### PR DESCRIPTION
**Pull request by n-rook**

### CODE REVIEW

**Comment by n-rook** [comment]
#75

**Review by 32th-System — APPROVED** [review]
I don't really know what any of this means  so I assume you know what you're doing

**Comment by n-rook** [comment]
csrf is important because javascript is really dumb, so it's a way to stop bad websites from sending requests to good websites and thus getting user data by tricking the user's browser https://docs.djangoproject.com/en/4.1/ref/csrf/

but it doesn't really apply to calls that aren't authorized via cookies or other stuff like that, and it stopped me from just sending a POST to do the autodeploy

**Comment by n-rook** [comment]
actually I'm slandering javascript. what's dumb is the standard for sending http calls through browsers. javascript is just dumb for unrelated reasons

**Pull request merged**
