### PR TITLE
Bugfix: Fix SA Marisa A power display

### PR DESCRIPTION
**Pull request by jgdhs27**
Currently, SA Marisa A's power is displayed as power/20, when it should be power/12.

To fix this, I introduced the parameter `shot_name` to `GetFormatPower`. I get the shot name via a call to `replay_instance.shot.GetName()` - I have no idea if this is correct or how to test that.

### CODE REVIEW

**Review by raviddog — APPROVED** [review]
Nice catch

**Comment by jgdhs27** [comment]
I noticed that I have to use `shot_name == "Marisa A"` and not `shot_name == "MarisaA"`. Does that mean it's using the translated string and will it break on different languages?

**Comment by raviddog** [comment]
> I noticed that I have to use `shot_name == "Marisa A"` and not `shot_name == "MarisaA"`. Does that mean it's using the translated string and will it break on different languages?

GetName() does appear to be calling GetShotName() which calls the pgettext functions, so that might be an issue. Looking at the model, it seems like the shot_id field is what you want

**Comment by jgdhs27** [comment]
> > I noticed that I have to use `shot_name == "Marisa A"` and not `shot_name == "MarisaA"`. Does that mean it's using the translated string and will it break on different languages?
> 
> GetName() does appear to be calling GetShotName() which calls the pgettext functions, so that might be an issue. Looking at the model, it seems like the shot_id field is what you want

Thanks, fixed it.

**Pull request merged**
